### ISSUE TITLE
Postgres version showing exredis error

### ISSUE THREAD

**Issue by johnkelly** [securingsincity/molasses#2]
Hey,

I'm using the latest published version `0.2.0` of molasses and followed the setup instructions in the README for using postgres/ecto instead of redis and I'm getting the error:

```
   ** (UndefinedFunctionError) function Exredis.Api.get/2 is undefined (module Exredis.Api is not available)
        Exredis.Api.get(ArticlesApi.Repo, "molasses_article_cache")
        (molasses) lib/adapters/redis.ex:37: Molasses.StorageAdapter.Redis.get_feature/2
        (molasses) lib/molasses.ex:68: Molasses.is_active/2
...
```

It seems to be using the `get_feature/2` from the redis adapter instead of the postgres adapter. I have set in my config/config.exs of my phoenix project:
```
config :molasses, adapter: "postgres"
```
I do not use exredis/redis and it is not included in my dependencies.

**Comment by securingsincity** [comment]
@johnkelly I'll take a look at this tonight. Thanks for the heads up.

**Comment by securingsincity** [comment]
@johnkelly just realized the issue 

```
# molasses adapter setting
config :molasses, adapter: "postgres" 
```

is wrong 

it should be 

```
# molasses adapter setting
config :molasses, adapter: "ecto" 
```

Will update the documentation to reflect that.

**Comment by johnkelly** [comment]
Great, thanks for looking into it. I'll try that tomorrow!

**Comment by securingsincity** [comment]
I also added the necessary migration in the readme. Going to close this issue out.
